-- Works only for Oracle
-- INDEX
CREATE INDEX EMP_ENAME ON EMP(ENAME);
SELECT index_name, table_name , uniqueness , index_type from user_indexes WHERE table_name = 'EMP';
DROP INDEX EMP_ENAME;

-- DCL
GRANT SELECT ON EMP TO HR; -- GRANT PERMISSION_TYPE ON TABLE_NAME TO USER
REVOKE SELECT ON EMP FROM HR; -- REVOKE PERMISSION_TYPE ON TABLE_NAME FROM USER

CONN SYS AS SYSDBA; -- ADMIN Login
CREATE USER SUDESHNA IDENTIFIED BY SUDESHNA; -- Create USER SUDESHNA
GRANT DBA TO SUDESHNA; -- GRANT Entire DB access to SUDESHNA
GRANT CREATE VIEW TO SCOTT;  -- GRANT Permission TO create View To Scott

-- View
CREATE VIEW TEST1 AS SELECT ENAME , DNAME FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO; -- Scott can now create a view
GRANT SELECT ON TEST1 TO HR; -- GRANT Permission To HR to perform reads on the VIEW TEST1
SELECT * FROM TEST1; -- HR can now see the results
DROP VIEW TEST1; -- Permanently delete, NOT SENT TO Recycle Bin, As View is a Virtual Table
SELECT * FROM TEST1;

-- Synonym
CREATE PUBLIC SYNONYM trial FOR scott.emp; -- Create Synonymn TRIAL For EMP
GRANT SELECT ON EMP TO HR; 
SELECT * FROM TRIAL; -- Now HR doesn't know the original table name, SECURE
DROP PUBLIC SYNONYM TRIAL;

-- SEQUENCE(CAN BE USED WITH/WITHOUT PRIMARY KEY)
CREATE SEQUENCE emp_seq
START WITH 5    -- START MUST BE GREATER THAN MINVALUE BUT LESS THAN MAXVALUE
INCREMENT BY 2
MINVALUE 3      -- COMPULSORY FOR CYCLE, AS AFTER ONE CYCLE COMPLETES IT STARTS FROM MINVALUE
MAXVALUE 20
CYCLE          -- 5 , 7 , 9 , .... , 19 , 3 , 5 , 7 , ...... , CANNOT BE USED WITH PRIMARY KEY
CACHE 8;       -- CACHE VALUE MUST BE LESS THAN ONE CYCLE SIZE

SELECT emp_seq.NEXTVAL from Dual;
SELECT emp_seq.CURRVAL from Dual;
DROP SEQUENCE emp_seq;
-- insert into emp values(emp_seq.NEXTVAL , "ABC", ...)

