SELECT * FROM TAB;

CREATE TABLE STUDENT
(
    SID CHAR(3) PRIMARY KEY CHECK(LENGTH(SID) = 3),
    SNAME VARCHAR(20),
    AGE INT CHECK(AGE > 18 AND AGE < 30)
)

DROP TABLE STUDENT; -- DELETE STUDENT, SEND IT TO RECYCLE BIN

SELECT * FROM RECYCLEBIN; -- View DELETED TABLES In Recycle Bin 

FLASHBACK TABLE STUDENT TO BEFORE DROP; -- RESTORE TABLE FROM RECYCLE BIN
PURGE TABLE STUDENT; -- PERMANENTLY DELETE TABLE FROM RECYCLE BIN

RENAME STUDENT TO STD;

TRUNCATE TABLE STD; -- DELETE DATA

ROLLBACK; -- WILL NOT WORK AFTER TRUNCATE

DROP TABLE STD PURGE; -- PERMANENTLY DELETE W/O SENDING TO RECYCLE BIN

CREATE TABLE EMP2 AS SELECT * FROM EMP;

SELECT * FROM EMP2;

CREATE TABLE EMP3 AS SELECT * FROM EMP WHERE ENAME = "Shreya"; -- TO COPY ONLY TABLE STRUCTURE
CREATE TABLE EMP3 AS SELECT * FROM EMP WHERE 1 = 2; -- ANY FALSE CONDITION TO ONLY COPY SCHEMA 

SELECT * FROM EMP3;

DESC STD;

ALTER TABLE STD ADD EMAIL VARCHAR(20) UNIQUE;
ALTER TABLE STD RENAME COLUMN EMAIL TO GMAIL;
DESC STD;
ALTER TABLE STD DROP COLUMN GMAIL;

CREATE TABLE COURSE(
CID CHAR(3) PRIMARY KEY,
CNAME VARCHAR(20)
);

ALTER TABLE STD DROP COLUMN CID;

ALTER TABLE STD ADD CID CHAR(3) references COURSE(CID);
DROP TABLE COURSE; -- NOT ALLOWED: We need to DROP Child TABLE FIRST

-- DDL(auto commited)
-- DML(Not auto-commited)
INSERT INTO COURSE(CID , CNAME) VALUES ('C01' , 'JFSD');
INSERT INTO COURSE(CID , CNAME) VALUES ('C02' , 'PFSD');
COMMIT; -- to commit
SELECT * FROM COURSE;

INSERT INTO EMP(EMPNO , ENAME , SAL) VALUES (1111 , 'ANKIT' , 4000);
ROLLBACK; -- ROLLBACK TO LAST COMMIT POINT
DELETE FROM EMP WHERE ENAME = "ANKIT";
SELECT * FROM EMP;

UPDATE EMP2 SET SAL = 1000;
UPDATE EMP2 SET SAL = 2000 WHERE ENAME = "SMITH";
DELETE FROM EMP2 WHERE SAL = 2000;
ROLLBACK;
SELECT * FROM EMP2;
