SELECT * FROM scott.emp;
-- SELECT JOB, DISTINCT SAL from scott.emp; ---> DISTINCT Should always be the first argument, here unequal no of rows in 2 columns
SELECT DISTINCT JOB, SAL from scott.emp;
select DISTINCT JOB FROM EMP;
-- select UNIQUE JOB FROM EMP; ----> works for ORACLE But not for MySQL
SELECT SAL*12 FROM EMP;
SELECT SAL - (SAL*10)/100 AS ANUAL_SAL FROM EMP;

-- ASSIGNMENT 1
SELECT * FROM EMP;
SELECT ENAME FROM EMP;
SELECT ENAME , SAL FROM EMP;
SELECT ENAME , COMM FROM EMP;
SELECT EMPNO , DEPTNO FROM EMP;
SELECT ENAME , HIREDATE FROM EMP;
SELECT ENAME , JOB FROM EMP;
SELECT ENAME , JOB , SAL FROM EMP;

-- ALIAS
SELECT SAL - (SAL*10/100) PENALTY FROM EMP;
SELECT SAL - (SAL*10/100) AS PENALTY FROM EMP;
-- SELECT SAL - (SAL*10/100) PENALTY_OF_10% FROM EMP; must use double quotes
SELECT SAL - (SAL*10/100) "PENALTY OF 10 %" FROM EMP; -- Oracle only supports double quotes
SELECT SAL - (SAL*10/100) "PENALTY_OF_10%" FROM EMP; --MySQL supports double , single , backtick
SELECT SAL - (SAL*10/100) `PENALTY_OF_10%` FROM EMP;
SELECT SAL - (SAL*10/100) 'PENALTY_OF_10%' FROM EMP;

-- ASSIGNMENT 2
SELECT ENAME NAME, SAL*12 ANNUAL_SALARY FROM EMP;
SELECT ENAME , JOB , SAL*6 "HALF TERM SALARY" FROM EMP;
SELECT * , SAL*12 + 2000 AS BONUS FROM EMP; 
-- SELECT EMP.* , SAL*12 + 2000 AS BONUS FROM EMP;  For Oracle
SELECT ENAME NAME , SAL SALARY, SAL + 10*SAL/100 HIKE FROM EMP;
SELECT ENAME NAME , SAL - SAL/4 DEDUCTED_SAL FROM EMP;
SELECT ENAME NAME , SAL + 50 HIKE FROM EMP;
SELECT ENAME NAME , SAL*12*90/100 AS DEDUCTED_SAL from emp;
SELECT ENAME NAME , SAL+COMM BONUS FROM EMP;
SELECT *, SAL*12 AS ANNUAL_SAL FROM EMP;
SELECT ENAME NAME, JOB DESIGNATION, SAL-100 PENALTY FROM EMP;





