SELECT * FROM scott.emp;
-- SELECTION
SELECT ename NAME, deptno FROM emp WHERE deptno = 20;
SELECT ename NAME, sal SALARY FROM emp WHERE sal > 3000;
SELECT ename NAME, sal SALARY FROM emp WHERE deptno = 10;
SELECT sal*12 SALARY FROM emp WHERE ename = "SMITH";
SELECT ename NAME FROM emp WHERE job = "CLERK";
SELECT sal SALARY FROM emp WHERE job = "SALESMAN";
SELECT * FROM emp WHERE sal > 2000;
SELECT * FROM emp WHERE ename = "JONES";
SELECT * FROM emp WHERE hiredate > "1981-01-01";
SELECT ename NAME, sal SALARY , sal*12 ANNUAL_SALARY from emp WHERE ANNUAL_SALARY > 12000;
SELECT empno FROM emp WHERE deptno = 30;
SELECT ename NAME, hiredate from emp WHERE hiredate < "1981-01-01";
SELECT * FROM emp where job = "MANAGER";
SELECT ename NAME , sal SALARY from emp WHERE comm = 1400;
SELECT * FROM emp WHERE comm > sal;
SELECT empno FROM emp WHERE hiredate < "1987-01-01";
SELECT * FROM emp WHERE job = "ANALYST";
SELECT * FROM emp WHERE sal > 2000;
SELECT SAL+COMM , COMM , SAL FROM EMP;

-- CONCATENATION
-- SELECT 'Hi ' || ENAME FROM EMP; -> Works only with ORACLE

-- LOGICAL OPERATORS
SELECT ename , deptno from emp WHERE job = "MANAGER" AND deptno = 10;
SELECT ENAME , DEPTNO from emp WHERE BINARY JOB = "MANAGER" AND DEPTNO = 10;
SELECT ENAME , DEPTNO , SAL FROM EMP WHERE DEPTNO = 20 AND SAL < 3000;
SELECT ENAME , DEPTNO FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20;
SELECT ENAME , SAL , DEPTNO FROM EMP WHERE SAL > 1250 AND SAL < 4000 AND DEPTNO = 20;
SELECT ENAME , JOB , DEPTNO FROM EMP WHERE (JOB = "MANAGER") AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT ENAME , DEPTNO , JOB  FROM EMP WHERE (DEPTNO = 10 OR DEPTNO = 20 OR DEPTNO = 30) AND JOB = "CLERK";
SELECT * FROM EMP WHERE NOT(JOB = "MANAGER" AND DEPTNO = 10);
SELECT * FROM EMP WHERE JOB <> "MANAGER" OR DEPTNO <> 10;
SELECT * FROM EMP WHERE JOB = "MANAGER" OR JOB = "SALESMAN" OR JOB = "CLERK";
SELECT ENAME FROM EMP WHERE HIREDATE >= "1982-01-01" AND HIREDATE < "1987-01-01";
SELECT * FROM EMP WHERE SAL > 1250 AND SAL < 3000;
SELECT ENAME FROM EMP WHERE HIREDATE >= "1981-01-01" AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT ENAME , sal*12 ANNUAL_SAL FROM EMP WHERE (JOB = "MANAGER" OR JOB = "CLERK") AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT *, sal*12 AS ANNUAL_SAL FROM EMP WHERE (sal*12 > 15000 AND SAL > 1000 AND SAL < 4000);

-- SPECIAL OPEARTORS
SELECT ENAME , DEPTNO FROM EMP WHERE DEPTNO IN (10, 30);
SELECT ENAME , JOB FROM EMP WHERE JOB IN("MANAGER" , "CLERK" , "SALESMAN");
SELECT ENAME , JOB FROM EMP WHERE JOB NOT IN("MANAGER" , "CLERK");
SELECT ENAME , DEPTNO FROM EMP WHERE DEPTNO NOT IN(10 , 40);
SELECT ENAME , SAL FROM EMP WHERE SAL BETWEEN 1000 AND 3000; -- BETWEEN LOWER AND UPPER LIMIT IS INCLUSIVE
SELECT ENAME , SAL FROM EMP WHERE SAL NOT BETWEEN 1000 AND 3000; -- NOT BETWEEN REJECT THE RANGE
SELECT ENAME FROM EMP WHERE HIREDATE BETWEEN "1982-01-01" AND "1986-12-31"; -- AFTER 1981 AND BEFORE 1987
SELECT ENAME FROM EMP WHERE COMM IS NULL; -- IS OPERATOR IS USED TO COMPARE WITH NULL
SELECT ENAME FROM EMP WHERE COMM IS NOT NULL; -- IS NOT TO COMPARE WITH NOT NULL
SELECT ENAME FROM EMP WHERE SAL IS NULL AND COMM IS NULL;
SELECT ENAME FROM EMP WHERE SAL IS NOT NULL;
SELECT ENAME , SAL , COMM FROM EMP WHERE COMM IS NULL AND SAL IS NOT NULL;

-- LIKE(PATTERN MATCHING)
SELECT * FROM EMP WHERE ENAME LIKE "S%";
SELECT * FROM EMP WHERE ENAME LIKE "%S";
SELECT * FROM EMP WHERE ENAME LIKE "%S%";
SELECT * FROM EMP WHERE ENAME LIKE "J%S";
SELECT * FROM EMP WHERE ENAME LIKE "_A%"; -- 2nd Letter A
SELECT * FROM EMP WHERE ENAME LIKE "__A%"; -- 3rd Letter A
SELECT * FROM EMP WHERE ENAME LIKE "%A_"; -- 2nd Last Letter A
SELECT * FROM EMP WHERE ENAME LIKE "_A%S"; -- 2nd Letter A , Last Letter S
SELECT * FROM EMP WHERE ENAME LIKE "%A%A%"; -- Atleast 2 A
SELECT * FROM EMP WHERE ENAME LIKE "%A%A%" AND ENAME NOT LIKE "%A%A%A%"; -- Exactly 2 A
SELECT SAL FROM EMP WHERE SAL LIKE '%50.00'; 
SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE LIKE "%-11-%";
SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE LIKE "_____11___";

-- ASSIGNMENT 1
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE mgr IS NULL;
SELECT * FROM EMP WHERE JOB = "SALESMAN" AND DEPTNO = 30;
SELECT * FROM EMP WHERE JOB = "SALESMAN" AND DEPTNO = 30 AND SAL > 1500;
SELECT * FROM EMP WHERE ENAME LIKE "S%" OR ENAME LIKE "A%";
SELECT * FROM EMP WHERE DEPTNO NOT IN(10 , 20);
SELECT * FROM EMP WHERE ENAME NOT LIKE "S%";
SELECT * FROM EMP WHERE MGR IS NOT NULL AND DEPTNO = 10;
SELECT * FROM EMP WHERE COMM IS NULL AND JOB = "CLERK";
SELECT * FROM EMP WHERE MGR IS NULL AND (DEPTNO = 10 OR DEPTNO = 30);
SELECT * FROM EMP WHERE JOB = "SALESMAN" AND DEPTNO = 30 AND SAL > 2450;
SELECT * FROM EMP WHERE JOB = "ANALYST" AND DEPTNO = 20 AND SAL > 2500;
SELECT * FROM EMP WHERE ENAME LIKE "M%" OR ENAME LIKE "J%";
SELECT * , SAL*12 ANNUAL_SAL FROM EMP WHERE DEPTNO <> 30;
SELECT * FROM EMP WHERE ENAME NOT LIKE "%ES" AND ENAME NOT LIKE "%R";
SELECT * , SAL*110/100 HIKE FROM EMP WHERE MGR IS NOT NULL AND DEPTNO = 10;
SELECT * FROM EMP WHERE ENAME LIKE "%E_" AND SAL LIKE "____.00" AND JOB = "SALESMAN";
SELECT * FROM EMP WHERE HIREDATE >= "1982-01-01";
SELECT * FROM EMP WHERE HIREDATE LIKE "%-02-%";
SELECT * FROM EMP WHERE JOB != "MANAGER" AND JOB != "CLERK" AND DEPTNO IN(10 , 20) AND SAL BETWEEN 1000 AND 3000;

-- MULTI ROW FUNCTION
-- 1. Accepts only one argument
SELECT MAX(SAL*12) FROM EMP;
SELECT MAX(SAL) , MAX(COMM) FROM EMP;

-- SELECT MAX(SAL), ENAME FROM EMP; -- 2. With MRF we cannot use a Column Name, unequal rows in each column

-- 3. MRF Ignores NULL
SELECT SUM(COMM) FROM EMP; 
SELECT COUNT(COMM) FROM EMP; 

-- SELECT ENAME FROM EMP WHERE Max(SAL) > 3000; --4. Cannot use MRF() in WHERE CLause

-- 4, COUNT(*) only MRF() that accepts *.
SELECT COUNT(*) FROM EMP; 

-- ASSIGNMENT 2
SELECT COUNT(*), SUM(Sal) FROM EMP WHERE ENAME like "%LL%";
SELECT COUNT(Distinct Deptno) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE "%Z%";
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE "%$%";
SELECT SUM(SAL) FROM EMP WHERE JOB = "CLERK" AND DEPTNO = 30;
SELECT MAX(SAL) FROM EMP WHERE JOB = "ANALYST";
SELECT COUNT(DISTINCT SAL) FROM EMP;
SELECT AVG(SAL) FROM EMP;
SELECT MIN(SAL) FROM EMP WHERE JOB = "MANAGER" OR JOB = "CLERK";

-- GROUP BY
SELECT DEPTNO , COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO , COUNT(*) FROM EMP WHERE JOB <> "ANANLYST" GROUP BY DEPTNO;
SELECT COUNT(*) , DEPTNO , JOB FROM EMP GROUP BY DEPTNO, JOB;
SELECT JOB, MAX(SAL) FROM EMP GROUP BY JOB;
SELECT JOB, COUNT(*) FROM EMP WHERE ENAME LIKE "%A%" GROUP BY JOB;
SELECT COUNT(*) , DEPTNO FROM EMP WHERE COMM IS NOT NULL GROUP BY DEPTNO;
SELECT COUNT(COMM) , DEPTNO FROM EMP GROUP BY DEPTNO;

-- ASSIGNMENT
SELECT COUNT(*), DEPTNO FROM EMP WHERE JOB <> "PRESIDENT" GROUP BY DEPTNO;
SELECT SUM(SAL), JOB FROM EMP GROUP BY JOB;
SELECT COUNT(*), DEPTNO FROM EMP WHERE JOB = "MANAGER" GROUP BY DEPTNO;
SELECT AVG(SAL), DEPTNO FROM EMP WHERE DEPTNO <> 20 GROUP BY DEPTNO;
SELECT COUNT(*), JOB FROM EMP WHERE ENAME LIKE "%A%" GROUP BY JOB;
SELECT COUNT(*), AVG(SAL), DEPTNO FROM EMP WHERE SAL > 2000 GROUP BY DEPTNO;
SELECT SUM(SAL) , COUNT(*) , DEPTNO FROM EMP WHERE JOB = "SALESMAN" GROUP BY DEPTNO;
SELECT COUNT(*) , MAX(SAL), JOB FROM EMP GROUP BY JOB;
SELECT MAX(SAL) , DEPTNO FROM EMP GROUP BY DEPTNO;
SELECT COUNT(*) , SAL from EMP GROUP BY SAL;

-- HAVING
SELECT COUNT(*) , DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*) >= 3;
SELECT COUNT(*) , DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*) >= 4;
SELECT COUNT(*)  FROM EMP HAVING MAX(SAL) > 3000;
SELECT COUNT(*) , JOB FROM EMP GROUP BY JOB HAVING COUNT(*) >= 2;
SELECT COUNT(*) , ENAME FROM EMP GROUP BY ENAME HAVING COUNT(*) > 1;
SELECT COUNT(*) , ENAME FROM EMP GROUP BY ENAME HAVING COUNT(*) = 2;
SELECT COUNT(*) , SAL FROM EMP GROUP BY SAL HAVING COUNT(*) > 1;

-- ASSIGNMENT
SELECT DEPTNO , COUNT(*) FROM EMP WHERE JOB = "CLERK" GROUP BY DEPTNO HAVING COUNT(*) = 2;
SELECT DEPTNO , SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING COUNT(*) >= 4;
SELECT COUNT(*) , JOB FROM EMP WHERE SAL > 1200 GROUP BY JOB HAVING SUM(SAL) > 3800;
SELECT COUNT(*) , DEPTNO FROM EMP WHERE JOB = "MANAGER" GROUP BY DEPTNO HAVING COUNT(*) = 2;
SELECT JOB , MAX(SAL) FROM EMP GROUP BY JOB HAVING MAX(SAL) > 2600;
SELECT SAL , COUNT(SAL) FROM EMP GROUP BY SAL HAVING COUNT(SAL) > 1;
SELECT HIREDATE , COUNT(HIREDATE) FROM EMP GROUP BY HIREDATE HAVING COUNT(HIREDATE) > 1;
SELECT AVG(SAL) , DEPTNO FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) < 3000;
SELECT COUNT(*) , DEPTNO FROM EMP WHERE ENAME LIKE "%A%" OR ENAME LIKE "%S%" group by DEPTNO HAVING COUNT(*) >= 3;
SELECT MIN(SAL) , MAX(SAL) , JOB FROM EMP GROUP BY JOB HAVING MIN(SAL) > 1000 AND MAX(SAL) < 5000;

-- SUB QUERY
SELECT ENAME , SAL FROM EMP WHERE SAL < ( SELECT SAL FROM EMP WHERE ENAME = "MILLER");
SELECT ENAME , DEPTNO FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME = "SMITH");
SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = "JONES");
SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME = "King");
SELECT ENAME , SAL , DEPTNO FROM EMP WHERE SAL > 2000 AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME = "JAMES");
SELECT * FROM EMP WHERE SAL > 1500 AND JOB IN (SELECT JOB FROM EMP WHERE ENAME = "MILLER");
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = "SMITH") AND SAL < (SELECT SAL FROM EMP WHERE ENAME = "KING");
SELECT ENAME FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = "JAMES") AND SAL > (SELECT SAL FROM EMP WHERE ENAME = "ADAMS") AND JOB = (SELECT JOB FROM EMP WHERE ENAME = "MILLER") AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = "MARTIN");

-- CASE: 2 When data to be selected and condition to be executed are present in different table 
SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME = "ADAMS");
SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = "DALLAS");
SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = "SCOTT") AND DEPTNO = 20;
SELECT * FROM EMP WHERE JOB = "MANAGER" AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = "ACCOUNTING");
SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME = "MILLER") AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = "New York");
SELECT COUNT(*) FROM EMP WHERE JOB = "CLERK" AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME = "SMITH") AND SAL > (SELECT SAL FROM EMP WHERE ENAME = "KING") AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = "MARTIN") AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = "BOSTON");

SELECT ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
SELECT ENAME , SAL FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP);
SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP); -- 2nd Max Salary
SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)); -- 3rd Max Salary
-- Nested Sub Query
SELECT ENAME , SAL FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)); -- Multi Row function

-- ASSIGNMENT
SELECT MIN(SAL) FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP); -- 2nd Min Salary
SELECT MAX(SAL) FROM EMP WHERE SAL <(SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP))));
SELECT ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)));
SELECT EMPNO , SAL FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)); 
SELECT DNAME FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)))));
SELECT * FROM EMP WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EMP));
SELECT * FROM EMP WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP));
SELECT LOC FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP));
SELECT * FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE SAL > ((SELECT MIN(SAL) FROM EMP WHERE SAL >(SELECT MIN(SAL) FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP))))))));
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP))); -- 2nd Max Salary



