-- EMPLOYEE MANAGER RELATIONSHIPS
SELECT ENAME FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE ENAME = "ALLEN");
SELECT ENAME FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE ENAME = "SMITH"));
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE ENAME = "KING"));
SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = "ADAMS")));
SELECT ENAME FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = "KING");
SELECT ENAME , SAL FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = "JAMES");
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE JOB = "PRESIDENT"));
SELECT * FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = "MILLER"));

-- ASSIGNMENT
SELECT ENAME FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = "SMITH");
SELECT ENAME FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE ENAME = "ADAMS"));
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE ENAME = "JONES"));
SELECT SAL FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = "MILLER");
SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP WHERE ENAME = "SMITH")));
SELECT ENAME FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = "BLAKE");
SELECT COUNT(*) FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = "KING");
SELECT * FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = "JONES");
SELECT ENAME FROM EMP WHERE MGR IN (SELECT MGR FROM EMP WHERE ENAME = "BLAKE");
SELECT COUNT(*) FROM EMP WHERE MGR IN (SELECT MGR FROM EMP WHERE ENAME = "FORD");

-- CROSS JOIN
SELECT ENAME , DNAME FROM EMP , DEPT; -- Oracle 
SELECT ENAME , DNAME FROM EMP CROSS JOIN DEPT; -- ANSI Syntax

-- INNER JOIN
SELECT ENAME , DNAME FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO; -- ANSI Syntax
SELECT ENAME , DNAME FROM EMP , DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO; -- Oracle

SELECT ENAME , LOC FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO WHERE JOB = "MANAGER";
SELECT ENAME , SAL , DNAME FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO WHERE JOB = "CLERK" AND EMP.DEPTNO = 20 AND SAL > 1800;
SELECT ENAME , EMP.DEPTNO , DNAME , LOC FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO WHERE SAL > 2000 AND LOC = "NEW YORK";

-- LEFT JOIN 
SELECT ENAME , DNAME FROM DEPT LEFT JOIN EMP ON EMP.DEPTNO = DEPT.DEPTNO;
SELECT ENAME , DNAME FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

-- RIGHT JOIN
SELECT ENAME , DNAME FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

-- UNION(Datatype should match)
SELECT ENAME FROM EMP UNION SELECT ENAME FROM EMP;
SELECT ENAME FROM EMP UNION SELECT JOB FROM EMP;
SELECT ENAME FROM EMP UNION ALL SELECT ENAME FROM EMP;
-- SELECT ENAME FROM EMP INTERSECT SELECT ENAME FROM EMP;
-- SELECT ENAME FROM EMP INTERSECT SELECT JOB FROM EMP;

-- FULL JOIN
-- SELECT ENAME , DNAME FROM EMP FULL JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO; --Oracle, Mysql doesn't support FULL JOIN

-- FULL OUTER JOIN IN MYSQL
SELECT ENAME , DNAME FROM 
EMP LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT ENAME , DNAME FROM 
EMP RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- NATURAL JOIN
SELECT ENAME , DNAME FROM EMP NATURAL JOIN DEPT;

-- SELF JOIN
SELECT E.ENAME EMPLOYEE , M.ENAME MANAGER FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO;
SELECT E.ENAME EMPLOYEE, E.SAL , M.ENAME MANAGER, M.SAL FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO;
SELECT E.ENAME EMPLOYEE , E.DEPTNO, M.ENAME MANAGER , M.DEPTNO FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.JOB = "CLERK";
SELECT E.ENAME EMPLOYEE , M.JOB MANAGER_JOB FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE M.JOB = "ANALYST";

SELECT E.ENAME EMPLOYEE , M.ENAME MANAGER , DE.DNAME 
FROM EMP E JOIN EMP M 
ON E.MGR = M.EMPNO JOIN DEPT DE 
ON E.DEPTNO = DE.DEPTNO;

SELECT E.ENAME EMPLOYEE , M.ENAME MANAGER , DE.DNAME , DM.DNAME 
FROM EMP E JOIN EMP M 
ON E.MGR = M.EMPNO JOIN DEPT DE 
ON E.DEPTNO = DE.DEPTNO JOIN DEPT DM 
ON M.DEPTNO = DM.DEPTNO;



