SELECT * FROM scott.emp;
SELECT * FROM EMP ORDER BY EMPNO desc;
SELECT * FROM EMP ORDER BY ENAME;
SELECT JOB , DEPTNO FROM EMP ORDER BY JOB asc, DEPTNO desc; -- Precedence given to first

-- only for oracle
-- LEVEL only works if we use CONNECT BY
-- SELECT ENAME , LEVEL
-- FROM EMP
-- START WITH ENAME = "KING"
-- CONNECT BY PRIOR EMPNO = MGR;

-- SELECT ENAME , LEVEL
-- FROM EMP
-- START WITH ENAME = "JONES"
-- CONNECT BY PRIOR MGR = EMPNO;

-- LEVEL IS DYNAMICALLY GENERATED WHILE EXECUTING THE SELECT QUERY , SO WE MAKE IT STATIC (L)TO ACCESS IT
-- SELECT * FROM(SELECT ENAME , LEVEL L
-- 				FROM EMP
-- 				START WITH ENAME = "KING"
-- 				CONNECT BY PRIOR EMPNO = MGR) WHERE L = 2;

-- Single Row Functions
-- 1.LENGTH()
SELECT LENGTH('RAJ') FROM DUAL;
SELECT ENAME , LENGTH(ENAME) FROM EMP;
SELECT ENAME FROM EMP WHERE LENGTH(ENAME) = 4;
SELECT ENAME FROM EMP WHERE LENGTH(ENAME) = (SELECT MAX(LENGTH(ENAME)) FROM EMP);

-- 2.CONCAT()
SELECT CONCAT('HI ' , ENAME) FROM EMP;
SELECT CONCAT('HI' , CONCAT(' ' , ENAME)) FROM EMP;
SELECT CONCAT('HI ' , CONCAT('GOOD MORNING' , ENAME)) FROM EMP;
SELECT CONCAT('HI ' , 'GOOD MORNING ' , ENAME) FROM EMP; -- Doesn't work for Oracle

-- 3.UPPER()
-- 4.LOWER()
-- 5.INITCAP()
-- Only for Orcale as it is Case Sensitive, For MySQL Every scenario will work bcoz it's case insensitive.
SELECT * FROM EMP WHERE UPPER(ENAME) = 'ALLEN';
SELECT * FROM EMP WHERE LOWER(ENAME) = 'allen';
SELECT * FROM EMP WHERE initcap(ENAME) = 'Allen'; -- ONLY FOR SQL

SELECT * FROM EMP WHERE BINARY LOWER(ENAME) = 'ALLEN'; -- Now Mysql becomes case sensitive -> RETURNS 0 ROWS

-- 6. REVERSE()
SELECT REVERSE(ENAME) , ENAME FROM EMP;

-- 7. SUBSTR()
SELECT SUBSTR('MALAYALAM' , 1 , 4) FROM DUAL; 
SELECT SUBSTR('MALAYALAM' , 5 , 1) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , 5 , 2) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , 7) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , 5 , 1) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , LENGTH('MALAYALAM')) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , LENGTH('MALAYALAM')-1) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , -2) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , -2 , 1) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , -2 , 3) FROM DUAL;
SELECT SUBSTR('MALAYALAM' , -4 , 2) FROM DUAL;

SELECT SUBSTR(ENAME , 1 , 2) , ENAME FROM EMP;
SELECT SUBSTR(ENAME , 2 , 1) , ENAME FROM EMP;
SELECT SUBSTR(ENAME , -1) , ENAME FROM EMP;
SELECT ENAME FROM EMP WHERE SUBSTR(ENAME , 1 , 1) IN ('A' , 'S');

-- 8.REPLACE()
SELECT REPLACE('MALAYALAM' , 'A' , 'Z') FROM DUAL;
SELECT REPLACE('MALAYALAM' , 'A' , '') FROM DUAL;

-- 9.MOD()
SELECT MOD(5 , 3) FROM DUAL;
SELECT ENAME , EMPNO FROM EMP WHERE MOD(EMPNO , 2) = 1;
SELECT ENAME , EMPNO FROM EMP WHERE MOD(EMPNO , 2) = 0;
SELECT ENAME , LENGTH(ENAME) FROM EMP WHERE MOD(LENGTH(ENAME) , 2) = 1;

-- 10.TRUNC() for Oracle , TRUNCATE() for MySQL
SELECT TRUNCATE(123.45 , 0) FROM DUAL; -- 123
SELECT TRUNCATE(123.45 , 1) FROM DUAL; -- 123.4
SELECT TRUNCATE(123.999 , 2) FROM DUAL; -- 123.99
SELECT TRUNCATE(123.9999 , 1) FROM DUAL; -- 123.9

-- 11. ROUND()
SELECT ROUND(123.45) FROM DUAL; -- 123
SELECT ROUND(123.45 , 1) FROM DUAL; -- 123.5
SELECT ROUND(123.899 , 2) FROM DUAL; -- 123.90

-- 12. MONTHS_BETWEEN() only for oracle
SELECT sysdate() FROM DUAL;
SELECT MONTHS_BETWEEN(SYSDATE , '2025-01-19') FROM DUAL; -- 12
SELECT MONTHS_BETWEEN(SYSDATE , HIREDATE)/12 FROM DUAL; 
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE , HIREDATE)/12) FROM DUAL; 
SELECT ENAME FROM EMP WHERE TRUNC(MONTHS_BETWEEN(SYSDATE , HIREDATE)/12) < 40;

-- 13. LAST_DAY() only for oracle
SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- 14. TO_CHAR() only for oracle 
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'YEAR') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'YYYY-MM') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'YYYY-MM-DY') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'D') FROM DUAL;
SELECT ENAME FROM EMP WHERE TO_CHAR(HIREDATE , 'D') = 4; -- Hired on Wednesaday
SELECT TO_CHAR(SYSDATE , 'HH12') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'HH24') FROM DUAL;
SELECT TO_CHAR(SYSDATE , 'HH24:MI:SS') FROM DUAL;
-- UNION only works for same datatype in oracle
SELECT ENAME FROM EMP 
UNION
SELECT TO_CHAR(SAL) FROM EMP;

-- 15. NVL() only for oracle 
SELECT SAL , COMM , SAL+NVL(COMM , 0) FROM EMP;
SELECT SAL , COMM , SAL+NVL(COMM , 10) FROM EMP;

SELECT SAL , COMM , SAL+coalesce(COMM , 0) FROM EMP; -- FOR MYSQL(ANSI)

-- 16. INSTR() - 4 params only for oracle
SELECT instr('MALAYALAM', 'A', 1, 1) FROM DUAL; -- 2  -- POSITION, OCCURANCE
SELECT instr('MALAYALAM', 'A', 3, 1) FROM DUAL; -- 4
SELECT instr('MALAYALAM', 'A', 3, 2) FROM DUAL; -- 6 -- FROM 3rd POSITION , 2nd Occurance

SELECT ENAME FROM EMP WHERE INSTR(ENAME , 'A' , 1 , 2) > 0; -- ATLEAST 2 A in names
SELECT ENAME FROM EMP WHERE INSTR(ENAME , 'A' , 1 , 1) > 0; -- ATLEAST 1 A in names








