-- SELF JOIN
SELECT E.ENAME EMPLOYEE, M.ENAME MANAGER FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.JOB = "CLERK";
SELECT E.ENAME EMPLOYEE, M.JOB MANAGER_DESIGNATION FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE M.DEPTNO IN (10 , 20);
SELECT E.ENAME EMPLOYEE, E.SAL , M.SAL FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.SAL > 2300 AND M.SAL > 2300;
SELECT E.ENAME EMPLOYEE, M.HIREDATE MANAGER_HIREDATE FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.HIREDATE < "1982-01-01";
SELECT E.ENAME EMPLOYEE, M.COMM MANAGER_COMM FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.JOB = "SALESMAN" AND M.DEPTNO = 30;
SELECT E.ENAME EMPLOYEE, E.SAL EMPLOYEE_SAL, M.ENAME MANAGER, M.SAL MANAGER_SALARY FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.SAL > M.SAL;
SELECT E.ENAME EMPLOYEE, E.HIREDATE HIREDATE, M.ENAME MANAGER, M.HIREDATE HIREDATE FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE M.HIREDATE < E.HIREDATE;
SELECT E.ENAME EMPLOYEE, M.ENAME MANAGER FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.JOB = M.JOB;
SELECT E.ENAME EMPLOYEE, M.ENAME MANAGER , M.JOB MANAGER_JOB FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE M.JOB = "MANAGER";
SELECT E.ENAME EMPLOYEE, E.SAL*12 , M.ENAME MANAGER , M.SAL*12 FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE E.DEPTNO IN (10 , 20) AND M.SAL > E.SAL;
SELECT E.ENAME EMPLOYEE, M.JOB MANAGER_DESIGNATION FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO;
SELECT E.ENAME , M.SAL FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO WHERE M.SAL LIKE "%50.00";

-- INNER JOIN
SELECT ENAME , LOC FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
SELECT DNAME , SAL FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE DNAME = "ACCOUNTING";
SELECT DNAME , SAL , SAL*12 ANNUAL_SAL FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE SAL > 2340;
SELECT ENAME , DNAME FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE ENAME LIKE "%A%";
SELECT ENAME , DNAME FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE JOB = "SALESMAN";
SELECT DNAME , JOB FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE JOB LIKE "S%" AND DNAME LIKE SUBSTR(DNAME , 1 , 1) = 'S';
SELECT DNAME , MGR FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE MGR = 7839;
SELECT DNAME , HIREDATE FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE HIREDATE >= "1984-01-01" AND DNAME IN ("ACCOUNTING" , "RESEARCH");
SELECT ENAME , DNAME FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE E.COMM IS NOT NULL AND E.DEPTNO IN (10 , 30);
SELECT DNAME , EMPNO FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE E.EMPNO IN (7839 , 7902) AND LOC = "NEW YORK"